// autogenerated by typings-for-css-modules-loader.
declare namespace PaletteModuleScssNamespace {
  export interface IPaletteModuleScss {
    '-accent-green-100': string;
    '-accent-green-200': string;
    '-accent-green-300': string;
    '-accent-green-500': string;
    '-accent-green-700': string;
    '-accent-green-900': string;
    '-accent-red-100': string;
    '-accent-red-200': string;
    '-accent-red-300': string;
    '-accent-red-500': string;
    '-accent-red-700': string;
    '-accent-red-900': string;
    '-accent-yellow-100': string;
    '-accent-yellow-200': string;
    '-accent-yellow-300': string;
    '-accent-yellow-500': string;
    '-accent-yellow-700': string;
    '-accent-yellow-900': string;
    '-grey-200': string;
    '-grey-300': string;
    '-grey-400': string;
    '-grey-500': string;
    '-grey-600': string;
    '-grey-700': string;
    '-grey-800': string;
    '-grey-900': string;
    '-primary-100': string;
    '-primary-200': string;
    '-primary-300': string;
    '-primary-400': string;
    '-primary-500': string;
    '-primary-600': string;
    '-primary-700': string;
    '-primary-800': string;
    '-primary-900': string;
    accentGreen100: string;
    accentGreen200: string;
    accentGreen300: string;
    accentGreen500: string;
    accentGreen700: string;
    accentGreen900: string;
    accentRed100: string;
    accentRed200: string;
    accentRed300: string;
    accentRed500: string;
    accentRed700: string;
    accentRed900: string;
    accentYellow100: string;
    accentYellow200: string;
    accentYellow300: string;
    accentYellow500: string;
    accentYellow700: string;
    accentYellow900: string;
    box: string;
    grey200: string;
    grey300: string;
    grey400: string;
    grey500: string;
    grey600: string;
    grey700: string;
    grey800: string;
    grey900: string;
    palette: string;
    primary100: string;
    primary200: string;
    primary300: string;
    primary400: string;
    primary500: string;
    primary600: string;
    primary700: string;
    primary800: string;
    primary900: string;
  }
}

declare const PaletteModuleScssModule: PaletteModuleScssNamespace.IPaletteModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PaletteModuleScssNamespace.IPaletteModuleScss;
};

export = PaletteModuleScssModule;
